source 'https://rubygems.org'
ruby '2.1.0'

gem 'sprockets', github: 'sstephenson/sprockets'

gem 'soupcms-cli', github: 'soupcms/soupcms-cli'
gem 'soupcms-common', github: 'soupcms/soupcms-common'
gem 'soupcms-core', github: 'soupcms/soupcms-core'
gem 'soupcms-api', github: 'soupcms/soupcms-api'

gem 'kramdown'
gem 'coderay'
gem 'nokogiri'
gem 'mongo'
gem 'bson_ext'
gem 'puma'